### ISSUE TITLE
Not compatible with scalajs-react 1.x.x+

### ISSUE THREAD

**Issue by aleastChs** [aleastChs/scalajs-google-charts#17]
Versions that I get to work with facade 
val scalaJSReactVersion = "0.11.3"
val scalaCssVersion = "0.5.1"

When I change to 
scalajs-react v1.1.0,
scalacss v0.5.3,

I get strange errors on the gui-side like:
Uncaught $c_jl_AssertionError

**Comment by aleastChs** [comment]
$ Hej Google Charts Mount spgui-fastopt.js:87576 
           undefined spgui-fastopt.js:213 

$ Uncaught $c_sjsr_UndefinedBehaviorErrore$1: $c_jl_ClassCastException 
{s$1: "undefined is not an instance of java.lang.Boolean", e$1: null, stackTrace$1: null, stackdata: $c_jl_ClassCastException, 
stack: "Error↵    at $c_jl_ClassCastException.$c_jl_Throwa…t:8080/target/scala-2.11/spgui-fastopt.js:6799:69"}s$1: 
"An undefined behavior was detected: undefined is not an instance of java.lang.Boolean"stackTrace$1: nullstackdata: 
$c_sjsr_UndefinedBehaviorError {s$1: "An undefined behavior was detected: undefined is not an instance of java.lang.Boolean", e$1: $c_jl_ClassCastException, stackTrace$1: null, stackdata: 
$c_sjsr_UndefinedBehaviorError, stack: "Error↵    at $c_sjsr_UndefinedBehaviorError.$c_jl_…8080/target/scala-2.11/spgui-fastopt.js:28358:264"}stack: 
"Error↵    at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:36385:14)↵    
   at $c_sjsr_UndefinedBehaviorError.fillInStackTrace__jl_Throwable (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:86046:67)↵    
at $c_sjsr_UndefinedBehaviorError.$c_jl_Throwable.init___T__jl_Throwable (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:36407:8)↵    
at $c_sjsr_UndefinedBehaviorError.init___T__jl_Throwable (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:86053:52)↵    
at $c_sjsr_UndefinedBehaviorError.init___jl_Throwable (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:86049:67)↵    at $throwClassCastException (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:213:46)↵    at $asBoolean (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:639:5)↵    
at $uZ (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:682:12)↵    
at $c_Lspgui_widgets_charts_PatientGanttWidget$Backend.onMount__F0 (http://localhost:8080/target/scala-2.11/spgui-fastopt.js:28469:7)↵    
at http://localhost:8080/target/scala-2.11/spgui-fastopt.js:28358:264"__proto__: $c_jl_Error 3 spgui-fastopt.js:87576 
$ Websocket is: true

**Comment by aleastChs** [comment]
Fixed with local js-script
